apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: list-rbac-clusterrole
rules:
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["*"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: list-rbac-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: full-access-service-account
  namespace: default
roleRef:
  kind: ClusterRole
  name: list-rbac-clusterrole
  apiGroup: rbac.authorization.k8s.io

