apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: list-daemonsets-clusterrole
rules:
- apiGroups: ["apps"]
  resources: ["daemonsets"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: list-daemonsets-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: full-access-service-account
  namespace: default
roleRef:
  kind: ClusterRole
  name: list-daemonsets-clusterrole
  apiGroup: rbac.authorization.k8s.io

