apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-gcs
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
volumeBindingMode: WaitForFirstConsumer
provisioner: gcs.csi.ofek.dev
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
  csi.storage.k8s.io/node-publish-secret-name: csi-gcs-secret-mounter
  csi.storage.k8s.io/node-publish-secret-namespace: default
  csi.storage.k8s.io/provisioner-secret-name: csi-gcs-secret-creator
  csi.storage.k8s.io/provisioner-secret-namespace: default
  csi.storage.k8s.io/controller-expand-secret-name: csi-gcs-secret-creator
  csi.storage.k8s.io/controller-expand-secret-namespace: default
  gcs.csi.ofek.dev/location: asia-southeast1
  gcs.csi.ofek.dev/project-id: sagitta-401422
mountOptions:
  - --limit-ops-per-sec=-1
